### PR TITLE
Don't block on call to IsAuthorizedAsync in ResourceAuthorizeAttribute

### PR DESCRIPTION
**Pull request by adamkirkton**
Pull request to fix the issue described in Issue #66 

After calling the base implementation of OnAuthorizationAsync which in turn calls the synchronous OnAuthorization, if authorization fails then an HttpResponseMessage will have been set on the actionContext. If nothing has been set, then authorization has passed and we can do our additional checks and set the response if they fail.

### CODE REVIEW

**Comment by DavidParks8** [comment]
@adamkirkton there are code analysis warnings from the PR build. Please fix them.

**Comment by adamkirkton** [comment]
Hi @DavidParks8, what tool are you using for Code Analysis so I can find them and fix them?

**Comment by adamkirkton** [comment]
Ah, I think I found what you're talking about. I found how to dig into the Azure DevOps build. The two warnings that I see are for code that I did not modify and don't feel comfortable trying to change. They are for IsAuthorizedAsync in AuthorizationHelper. If you can't accept the PR in this case, I can just close it. Thanks!

**Comment by IlSocio** [comment]
@DavidParks8 any news about this PR?

**Review by sid1260 — APPROVED** [review]

**Comment by DavidParks8** [comment]
Deadlock has been fixed by a different commit.

**Pull request closed without merging**
